name: Actions secrets and variables
on: workflow_dispatch
jobs: 
  run-first-command:
      runs-on: ubuntu-latest
      steps:
        - name: Echo Vars
          run: |
            echo "${{secrets.ALL}}"
