name: Actions secrets and variables
on: push
jobs: 
  run-first-command:
      runs-on: ubuntu-latest
      environment: "production" 
      steps:
        - name: Echo Vars
          run: |
            echo "${{vars.STATUS}}"
            echo "${{secrets.PASSWORD}}"