name: Workflow Dispatch
on:
  workflow_dispatch:
    inputs:
      titleCustom:
        description: Type the title
        type: string
        required: true  
        default: "Hellow World!"
      selectCustom:
        description: Select Type
        required: true
        default: "Value 1"
        type: choice
        options:
          - Value 1
          - Value 2
          - Value 3
      checkBox:
        description: Check Box
        required: true
        type: boolean

jobs: 
  run-first-command:
      runs-on: ubuntu-latest
      steps:
        - name: Event Vars
          run: |
            echo "Title: ${{inputs.titleCustom}}"
            echo "Choice is ${{inputs.selectCustom}}"
            echo "Check Box is ${{inputs.checkBox}}"