name: Docker project 
on: workflow_dispatch
jobs: 
  build:
      runs-on: ubuntu-latest
      steps:
        - name: Clone git project 
          run: git clone https://github.com/taigaio/taiga-docker.git
        - name: Run scripts
          run: |
              cd taiga-docker/
              git checkout stable
              sed -i '/&default-back-environment/,/^$/!b;/^$/i \  PUBLIC_REGISTER_ENABLED: "True"' docker-compose.yml
              sed -i '/taiga-front:/,/environment:/!b;/environment:/a \      PUBLIC_REGISTER_ENABLED: "true"' docker-compose.yml
        - name: Check docker-image
          run: cat docker-compose.yml  
            
