name: Docker project 
on: workflow_dispatch
jobs: 
  build:
      runs-on: ubuntu-latest
      steps:
        - name: Clone git project 
          run: git clone https://github.com/taigaio/taiga-docker.git
          
        - name: Run scripts
          run: |
              cd taiga-docker
              git checkout stable
              sed -i '/&default-back-environment/,/^$/!b;/^$/i \  PUBLIC_REGISTER_ENABLED: "True"' docker-compose.yml
              sed -i '/taiga-front:/,/TAIGA_SUBPATH:/!b;/TAIGA_SUBPATH:/a \      PUBLIC_REGISTER_ENABLED: "true"' docker-compose.yml
              ./launch-all.sh
              timeout 60s bash -c 'while [[ "$(curl -s -o /dev/null -w ''%{http_code}'' http://localhost:9000/api/v1/)" != "200" ]]; do sleep 2; done' || false
        - name: Curl
          run: |
            curl http://localhost:9000/api/v1/projects
            curl -s -o /dev/null -w "%{http_code}" http://localhost:9000/api/v1/projects
        - name: Curl 2
          run: |
            curl http://localhost:9000
        - name: Curl 3
          run: |
            curl http://localhost:9000/api/v1/auth
          
