name: Docker project 
on: workflow_dispatch
jobs: 
  build:
      runs-on: ubuntu-latest
      steps:
        - name: Clone git project 
          run: git clone https://github.com/taigaio/taiga-docker.git
        - name: Run scripts
          run: |
              cd taiga-docker/
              git checkout stable
              ./launch-taiga.sh
    
        - name: Curl
          run: |
            curl http://localhost:9000/api/v1
            curl -s -o /dev/null -w "%{http_code}" http://localhost:9000/api/v1
            
