name: Docker project 
on: workflow_dispatch
jobs: 
  build:
      runs-on: ubuntu-latest
      steps:
        - name: Clone git project 
          run: git clone https://github.com/taigaio/taiga-docker.git
        - name: Run scripts
          run: |
              cd taiga-docker/
              git checkout stable
              sed -i '/&default-back-environment/,/^$/!b;/^$/i \  PUBLIC_REGISTER_ENABLED: "True"' docker-compose.yml
              sed -i '/taiga-front:/,/TAIGA_SUBPATH:/!b;/TAIGA_SUBPATH:/a \      PUBLIC_REGISTER_ENABLED: "true"' docker-compose.yml
              ./launch-all.sh
        - name: Curl
          run: |
            curl http://localhost:9000/api/v1
            curl -s -o /dev/null -w "%{http_code}" http://localhost:9000/api/v1
            
