name: Docker project 
on: workflow_dispatch
jobs: 
  build:
      runs-on: ubuntu-latest
      steps:
        - name: Clone git project 
          run: git clone https://github.com/taigaio/taiga-docker.git
          
        - uses: actions/checkout@v1
        - name: Run scripts
          run: |
              cd taiga-docker/
              git checkout stable
              docker-compose up
    
        - name: Curl
          run: |
            curl http://localhost:9000/api/v1/projects
            curl -s -o /dev/null -w "%{http_code}" http://localhost:9000/api/v1/projects
        - name: Curl 2
          run: |
            curl http://localhost:9000
        - name: Curl 3
          run: |
            curl http://localhost:9000/api/v1/auth
          
