name: Docker project 
on: workflow_dispatch
jobs: 
  build:
      runs-on: ubuntu-latest
      steps:
        - name: Clone git project 
          run: git clone https://github.com/taigaio/taiga-docker.git
        - name: Run scripts
          run: |
              cd taiga-docker/
              git checkout stable
              ./launch-all.sh
              ./taiga-manage.sh createsuperuser
        - name: Check work
          run: curl -v http://localhost:9000        
            
