name: First Workflow
on: workflow_dispatch
jobs: 
  run-first-command:
      runs-on: ubuntu-latest
      steps:
        - name: Display Some Text
          run: echo "Some Text"
        - name: Comman №2
          run: |
            node -v
            npm -v