name: Third Workflow
on: push
jobs: 
  run-first-command:
      runs-on: ubuntu-latest
      steps:
        - name: Display list of files
          run: ls -a
        - uses: actions/checkout@v4
        - name: List file
          run: ls -a